@startuml
set namespaceSeparator ::

class "fbs::core::app_colors.dart::AppColors" {
  {static} +Color navy
  {static} +Color gold
  {static} +Color lightGold
  {static} +Color white
  {static} +Color background
  {static} +Color inputFill
}

"fbs::core::app_colors.dart::AppColors" o-- "dart::ui::Color"

class "fbs::core::asset_service.dart::AssetService" {
  {static} -List<Asset> _assets
  {static} +List<Asset> getAllAssets()
  {static} +Asset? getAssetById()
  {static} +String generateUniqueId()
  {static} -String _getCampusCode()
  {static} -String _getCategoryCode()
  {static} +void updateAsset()
  {static} +void addAsset()
  {static} +void linkReportToAsset()
}

class "fbs::core::auth_config.dart::AuthConfig" {
  {static} +String clientId
  {static} +String tenantId
  {static} +String redirectUri
  {static} +List<String> scopes
}

class "fbs::core::camera_service.dart::CameraService" {
  {static} -ImagePicker _picker
  {static} +dynamic takePhoto()
  {static} +dynamic pickFromGallery()
}

"fbs::core::camera_service.dart::CameraService" o-- "image_picker::image_picker.dart::ImagePicker"

class "fbs::core::map_cache_manager.dart::MapCacheManager" {
  {static} -CacheStore? _store
  {static} +dynamic getCacheStore()
}

"fbs::core::map_cache_manager.dart::MapCacheManager" o-- "http_cache_core::src::store::cache_store.dart::CacheStore"

class "fbs::core::report_service.dart::ReportService" {
  {static} +ValueNotifier<List<Map<String, String>>> reportsNotifier
  {static} +int count
  {static} +int pendingCount
  {static} +int highPriorityCount
  {static} +void addReport()
  {static} +void approveReport()
  {static} +void disapproveReport()
  {static} +void updateReportPriority()
}

"fbs::core::report_service.dart::ReportService" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<List<Map<String, String>>>"

class "fbs::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::main.dart::MyApp"

class "fbs::models::asset.dart::Asset" {
  +String id
  +String name
  +String category
  +String location
  +String status
  +DateTime purchaseDate
  +DateTime campusStartDate
  +List<String> warrantyReceipts
  +List<String> reportIds
  +Map<String, dynamic> toJson()
}

class "fbs::models::user_session.dart::UserSession" {
  {static} +bool isAdmin
  {static} +String userName
  {static} +String userCampus
}

class "fbs::pages::assets::assets_page.dart::AssetsPage" {
  +State<AssetsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::assets::assets_page.dart::AssetsPage"

class "fbs::pages::assets::assets_page.dart::_AssetsPageState" {
  -TextEditingController _searchController
  +List<dynamic> filteredAssets
  +void initState()
  -void _filterAssets()
  +void dispose()
  +Widget build()
  -Widget _buildEmptyState()
  -Widget _statusBadge()
}

"fbs::pages::assets::assets_page.dart::_AssetsPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::assets::assets_page.dart::_AssetsPageState"

class "fbs::pages::assets::asset_detail_page.dart::AssetDetailPage" {
  +Asset asset
  +Widget build()
  -Widget _buildInfoCard()
  -Widget _buildSectionHeader()
  -Widget _buildDetailRow()
  -Widget _buildDocThumbnail()
  -void _showFullCode()
  -Widget _statusBadge()
}

"fbs::pages::assets::asset_detail_page.dart::AssetDetailPage" o-- "fbs::models::asset.dart::Asset"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::pages::assets::asset_detail_page.dart::AssetDetailPage"

class "fbs::pages::assets::new_asset_page.dart::NewAssetPage" {
  +State<NewAssetPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::assets::new_asset_page.dart::NewAssetPage"

class "fbs::pages::assets::new_asset_page.dart::_NewAssetPageState" {
  -GlobalKey<FormState> _formKey
  +String name
  +String category
  +String campus
  +String location
  +DateTime purchaseDate
  +DateTime campusDate
  +String? generatedId
  +bool isFixed
  +List<String> categories
  +List<String> campuses
  -void _generateId()
  +Widget build()
}

"fbs::pages::assets::new_asset_page.dart::_NewAssetPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::assets::new_asset_page.dart::_NewAssetPageState"

class "fbs::pages::auth::forgot_password_page.dart::ForgotPasswordPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::pages::auth::forgot_password_page.dart::ForgotPasswordPage"

class "fbs::pages::auth::login_page.dart::LoginPage" {
  +State<LoginPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::auth::login_page.dart::LoginPage"

class "fbs::pages::auth::login_page.dart::_LoginPageState" {
  +LocalAuthentication auth
  -bool _isLoading
  -bool _canCheckBiometrics
  +AadOAuth oauth
  -TextEditingController _userControl
  -TextEditingController _passControl
  +Config config
  +void initState()
  -dynamic _initAuth()
  -dynamic _authenticateWithBiometrics()
  -dynamic _navigateToHome()
  -dynamic _showBiometricPrompt()
  -dynamic _outlookLogin()
  +Widget build()
  -Widget _buildInputLabel()
  -Widget _microsoftIcon()
  -Widget _colorBox()
}

"fbs::pages::auth::login_page.dart::_LoginPageState" o-- "local_auth::src::local_auth.dart::LocalAuthentication"
"fbs::pages::auth::login_page.dart::_LoginPageState" o-- "aad_oauth::aad_oauth.dart::AadOAuth"
"fbs::pages::auth::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"fbs::pages::auth::login_page.dart::_LoginPageState" o-- "aad_oauth::model::config.dart::Config"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::auth::login_page.dart::_LoginPageState"

class "fbs::pages::home::dashboard_page.dart::DashboardPage" {
  +Widget build()
  -Widget _buildStatCard()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::pages::home::dashboard_page.dart::DashboardPage"

class "fbs::pages::home::home_page.dart::HomePage" {
  +State<HomePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::home::home_page.dart::HomePage"

class "fbs::pages::home::home_page.dart::_HomePageState" {
  -int _selectedIndex
  -List<Map<String, dynamic>> _getVisibleMenu()
  +Widget build()
  -Widget _drawerItem()
}

"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::home::home_page.dart::_HomePageState"

class "fbs::pages::reporting::leriba_sitemap_page.dart::LeribaSitemapPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::pages::reporting::leriba_sitemap_page.dart::LeribaSitemapPage"

class "fbs::pages::reporting::location_page.dart::Campus" {
  +String name
  +LatLng location
  +double radius
  +String? imageAsset
}

"fbs::pages::reporting::location_page.dart::Campus" o-- "latlong2::latlong.dart::LatLng"

class "fbs::pages::reporting::location_page.dart::LocationPage" {
  +bool autoConfirm
  +State<LocationPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::reporting::location_page.dart::LocationPage"

class "fbs::pages::reporting::location_page.dart::_LocationPageState" {
  -MapController _mapController
  -GlobalKey<State<StatefulWidget>> _mapBoundaryKey
  -StreamSubscription<Position>? _positionStream
  -List<Campus> _campuses
  -LatLng _selectedLocation
  -LatLng? _userLocation
  -Campus? _activeCampus
  -bool _isManualMode
  -bool _hasPoint
  -bool _isSnapping
  -bool _gpsPermissionDenied
  -LatLngBounds _getCampusBounds()
  +void initState()
  +void dispose()
  -dynamic _initGps()
  -void _startTracking()
  -void _handleNewPosition()
  -void _updateActiveCampus()
  -bool _isPointInsideAnyCampus()
  -dynamic _confirmLocation()
  +Widget build()
  -Widget _buildNoGpsPlaceholder()
  -Widget _buildMap()
}

"fbs::pages::reporting::location_page.dart::_LocationPageState" o-- "flutter_map::src::map::controller::map_controller.dart::MapController"
"fbs::pages::reporting::location_page.dart::_LocationPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<State<StatefulWidget>>"
"fbs::pages::reporting::location_page.dart::_LocationPageState" o-- "dart::async::StreamSubscription<Position>"
"fbs::pages::reporting::location_page.dart::_LocationPageState" o-- "latlong2::latlong.dart::LatLng"
"fbs::pages::reporting::location_page.dart::_LocationPageState" o-- "fbs::pages::reporting::location_page.dart::Campus"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::reporting::location_page.dart::_LocationPageState"

class "fbs::pages::reporting::new_report_page.dart::NewReportPage" {
  {static} +DateTime? lastSubmissionTime
  +State<NewReportPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::reporting::new_report_page.dart::NewReportPage"

class "fbs::pages::reporting::new_report_page.dart::_NewReportPageState" {
  +File? problemImage
  +String? gpsCoords
  +Uint8List? mapScreenshot
  +TextEditingController idController
  +TextEditingController titleController
  +TextEditingController descController
  +List<String> leribaLocations
  +String? selectedLocation
  +String? selectedCategory
  +String selectedPriority
  +bool isInvisibleCode
  +bool isUnknownLocation
  +bool showValidationErrors
  -bool _canSubmit
  -void _handleScanResult()
  +Widget build()
  -Widget _buildEmailStyleDescription()
  -Widget _buildCompactActionButton()
  -Widget _buildPrioritySelector()
  -Widget _buildSectionHeader()
  -Widget _buildLabel()
  -Widget _buildLabelWithAction()
  -Widget _buildAssetInput()
  -Widget _buildCategoryDropdown()
  -Widget _buildLocationInput()
  -Widget _buildScanButton()
}

"fbs::pages::reporting::new_report_page.dart::_NewReportPageState" o-- "dart::io::File"
"fbs::pages::reporting::new_report_page.dart::_NewReportPageState" o-- "dart::typed_data::Uint8List"
"fbs::pages::reporting::new_report_page.dart::_NewReportPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::reporting::new_report_page.dart::_NewReportPageState"

class "fbs::pages::reporting::reporting_page.dart::ReportingPage" {
  +State<ReportingPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::reporting::reporting_page.dart::ReportingPage"

class "fbs::pages::reporting::reporting_page.dart::_ReportingPageState" {
  -String _searchQuery
  -String _priorityFilter
  +Widget build()
  -Widget _buildSearchBar()
  -Widget _buildReportList()
  -Widget _buildStatusText()
  -void _handleNewReport()
}

"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::reporting::reporting_page.dart::_ReportingPageState"

class "fbs::pages::reporting::report_detail_page.dart::ReportDetailPage" {
  +Map<String, String> report
  +Uint8List? screenshot
  +Widget build()
  -Widget _buildStatusCard()
  -Widget _buildPriorityBadge()
  -Widget _buildApprovalAction()
  -void _showApprovalDialog()
  -Widget _buildSectionHeader()
  -Widget _buildDetailRow()
  -Widget _buildTimeline()
  -Widget _buildTimelineItem()
}

"fbs::pages::reporting::report_detail_page.dart::ReportDetailPage" o-- "dart::typed_data::Uint8List"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fbs::pages::reporting::report_detail_page.dart::ReportDetailPage"

class "fbs::pages::reporting::scan_page.dart::ScanPage" {
  +bool isLocation
  +State<ScanPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fbs::pages::reporting::scan_page.dart::ScanPage"

class "fbs::pages::reporting::scan_page.dart::_ScanPageState" {
  +MobileScannerController cameraController
  -bool _isDetected
  +void dispose()
  +Widget build()
}

"fbs::pages::reporting::scan_page.dart::_ScanPageState" o-- "mobile_scanner::src::mobile_scanner_controller.dart::MobileScannerController"
"flutter::src::widgets::framework.dart::State" <|-- "fbs::pages::reporting::scan_page.dart::_ScanPageState"

class "fbs::pages::reporting::scan_page.dart::BorderPainter" {
  +void paint()
  +bool shouldRepaint()
}

"flutter::src::rendering::custom_paint.dart::CustomPainter" <|-- "fbs::pages::reporting::scan_page.dart::BorderPainter"


@enduml